app:
  requestServer: lookout-work:10301
  log:
    level: DEBUG

databases:
  postgres:
    cloudSQL: true
    instanceConnectionName: srcd-public-staging:europe-west1:lookout-staging-primary
    serviceAccountSecret: cloudsql-proxy-credentials
    connectionDetailsSecret: lookout-typos-analyzer-postgres-connection-details

nodeSelector:
  srcd.host/app: lookout
