[package]
name = "method-chains"
version = "0.1.1"
authors = [""]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
anyhow = "1.0.41"
itertools = "0.10.1"
bstr = "0.2.16"